// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ensure the principal has an identity. Idempotent — generates a fresh
 * did:key on first call, returns the existing one thereafter.
 * 
 * Mirrors `sec init` (without the optional `--did did:web:...` flag, which
 * is a power-user case that can stay in the CLI for now).
 */
async initIdentity() : Promise<Result<IdentityState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Surface the current identity without generating one. Returns `None`
 * (serialized as `null`) if no identity exists yet — the front-end can
 * use this to decide whether to show onboarding or the main UI.
 */
async currentIdentity() : Promise<Result<IdentityState | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("current_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diagnostic — returns the absolute path to `~/.secretariat/`. Useful for
 * "open in Finder" buttons and for surfacing where keys live.
 */
async secretariatRoot() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("secretariat_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Claim a correspondence invite from a deep link or HTTPS URL.
 * 
 * Accepts either form:
 * - `secretariat://<host>/v0/invite/<token>` (deep link from landing page)
 * - `https://<host>/v0/invite/<token>` (raw HTTPS URL the inviter shared)
 * 
 * Generates a fresh identity if none exists yet (so a deep link click is
 * the only step a first-time recipient needs). Maps to the existing
 * `secretariat-core::application::claim_invite` use case.
 */
async claimInviteUrl(deepLinkOrUrl: string) : Promise<Result<InviteClaimReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_invite_url", { deepLinkOrUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List received envelopes (`~/.secretariat/inbox/`).
 */
async listInbox() : Promise<Result<EnvelopeListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_inbox") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the principal's review queue — outbox drafts awaiting a stamp.
 * Excludes already-stamped drafts (those are in flight to the relay)
 * and the `sent/` historical archive.
 */
async listReviewQueue() : Promise<Result<EnvelopeListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_review_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decrypt + return the body of an envelope file. Plaintext envelopes
 * pass through unchanged; encrypted envelopes are decrypted using the
 * local signing key (key never leaves the device).
 */
async readEnvelope(filePath: string) : Promise<Result<EnvelopeRead, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run one sync cycle against every registered relay. Pulls inbound
 * envelopes, auto-adds contacts from claim events, drains stamped
 * drafts from the outbox. Principal-initiated per the review-session
 * model — no background push.
 * 
 * Idempotent and safe to call repeatedly. Returns a report the UI can
 * surface (counts + non-fatal warnings).
 */
async syncNow() : Promise<Result<SyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the principal's profile. Returns null when no profile has been
 * set yet (fresh install pre-onboarding).
 */
async getProfile() : Promise<Result<Profile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the principal's display name. Idempotent — overwrites whatever
 * was there. The DisplayName parser enforces validity (non-empty,
 * reasonable length, etc.).
 */
async setProfile(displayName: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_profile", { displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an invite at the principal's first registered relay. Returns
 * the HTTPS claim URL the inviter shares (recipient's HTML landing
 * page lives at the same URL with `Accept: text/html`). Optional
 * `purpose` becomes the suggested contact name on the receiving side.
 */
async createInvite(purpose: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_invite", { purpose }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stampEnvelope(filePath: string) : Promise<Result<StampReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stamp_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an inbox envelope to `inbox/deferred/` — "remind me later".
 * Returns the new path. Idempotent.
 */
async deferInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("defer_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an inbox envelope to `inbox/archived/` — "ignore / handled".
 * Returns the new path. Idempotent.
 */
async archiveInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null }
export type EnvelopeListing = { file_path: string; from: string | null; to: string | null; stamped: boolean; encrypted: boolean }
export type EnvelopeRead = { body: string; from: string | null; to: string | null; was_encrypted: boolean }
/**
 * What `init_identity` reports back to the front-end.
 */
export type IdentityState = { 
/**
 * The principal's DID — `did:key:z…` for a fresh install.
 */
did: string; 
/**
 * Whether this call generated a new identity (true) or surfaced an
 * existing one (false). The UI uses this to switch between
 * "Welcome — your identity is …" vs "Welcome back — you're …".
 */
created: boolean }
export type InviteClaimReport = { inviter_did: string; claimant_did: string; claimed_at: string; 
/**
 * True when the relay registered this principal as part of the claim
 * (first-time onboarding). False when the principal was already a tenant.
 */
registered: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Profile = { display_name: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
export type RelaySyncReport = { endpoint: string; inbound_count: number; auto_added_contacts: number; warnings: string[] }
/**
 * Stamp an outbox draft and (best-effort) deliver it immediately. Touch
 * ID fires from the app's window context. Returns the relay-assigned
 * id on successful delivery, or stamp metadata only if delivery fails
 * (the daemon's next sync tick retries — same fallback as the CLI's
 * stamp-immediate-send path).
 */
export type StampReport = { stamped_path: string; doc_hash: string; stamped_at: string; delivered: boolean; 
/**
 * Relay-assigned envelope ID. String to avoid BigInt/JS-number
 * roundtripping (specta forbids `u64` directly).
 */
relay_assigned_id: string | null; delivery_warning: string | null }
export type SyncReport = { per_relay: RelaySyncReport[]; sent_envelopes: number; outbox_warnings: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
