// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ensure the principal has an identity. Idempotent — generates a fresh
 * did:key on first call, returns the existing one thereafter.
 * 
 * Mirrors `sec init` (without the optional `--did did:web:...` flag, which
 * is a power-user case that can stay in the CLI for now).
 */
async initIdentity() : Promise<Result<IdentityState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Surface the current identity without generating one. Returns `None`
 * (serialized as `null`) if no identity exists yet — the front-end can
 * use this to decide whether to show onboarding or the main UI.
 */
async currentIdentity() : Promise<Result<IdentityState | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("current_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diagnostic — returns the absolute path to `~/.secretariat/`. Useful for
 * "open in Finder" buttons and for surfacing where keys live.
 */
async secretariatRoot() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("secretariat_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Claim a correspondence invite from a deep link or HTTPS URL.
 * 
 * Accepts either form:
 * - `secretariat://<host>/v0/invite/<token>` (deep link from landing page)
 * - `https://<host>/v0/invite/<token>` (raw HTTPS URL the inviter shared)
 * 
 * Generates a fresh identity if none exists yet (so a deep link click is
 * the only step a first-time recipient needs). Maps to the existing
 * `secretariat-core::application::claim_invite` use case.
 */
async claimInviteUrl(deepLinkOrUrl: string) : Promise<Result<InviteClaimReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_invite_url", { deepLinkOrUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List received envelopes — walks the v0.3 substrate tree under
 * `~/.secretariat/` for every `envelopes/` directory and collects
 * the `.md` leaves.
 */
async listInbox() : Promise<Result<EnvelopeListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_inbox") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the principal's review queue — unstamped outbox drafts plus
 * every envelope on disk. Substrate v0.3 (namespace-symmetric
 * queues) unions per-queue `outbox/*.md` (drafts awaiting a stamp)
 * with per-queue `envelopes/*.md` (received letters + local
 * captures) under one substrate root. Both `to` and `queue` are
 * populated on every entry — discriminate local vs peer by
 * comparing `to` to the principal's own DID.
 */
async listReviewQueue() : Promise<Result<EnvelopeListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_review_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decrypt + return the body of an envelope file. Plaintext envelopes
 * pass through unchanged; encrypted envelopes are decrypted using the
 * local signing key (key never leaves the device).
 */
async readEnvelope(filePath: string) : Promise<Result<EnvelopeRead, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run one sync cycle against every registered relay. Pulls inbound
 * envelopes, auto-adds contacts from claim events, drains stamped
 * drafts from the outbox. Principal-initiated per the review-session
 * model — no background push.
 * 
 * Idempotent and safe to call repeatedly. Returns a report the UI can
 * surface (counts + non-fatal warnings).
 */
async syncNow() : Promise<Result<SyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the principal's profile. Returns null when no profile has been
 * set yet (fresh install pre-onboarding).
 */
async getProfile() : Promise<Result<Profile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the principal's display name. Idempotent — overwrites whatever
 * was there. The DisplayName parser enforces validity (non-empty,
 * reasonable length, etc.).
 */
async setProfile(displayName: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_profile", { displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an invite at the principal's first registered relay. Returns
 * the HTTPS claim URL the inviter shares (recipient's HTML landing
 * page lives at the same URL with `Accept: text/html`). Optional
 * `purpose` becomes the suggested contact name on the receiving side.
 */
async createInvite(purpose: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_invite", { purpose }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stampEnvelope(filePath: string) : Promise<Result<StampReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stamp_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an inbox envelope to `inbox/deferred/` — "remind me later".
 * Returns the new path. Idempotent.
 */
async deferInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("defer_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an inbox envelope to `inbox/archived/` — "ignore / handled".
 * Returns the new path. Idempotent.
 */
async archiveInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the principal's known contacts. The Sign-mode home surface
 * resolves recipient DIDs to display names through this; falls back to
 * truncated DID when a peer isn't yet in the contact book.
 */
async listContacts() : Promise<Result<ContactListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_contacts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn the principal's assistant in their preferred environment. Reads
 * `AppPreferences::assistant_terminal` + `assistant_command` from the
 * caller; defaults to Terminal.app + `claude`.
 */
async launchAssistant(terminal: string | null, command: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_assistant", { terminal, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every vault the principal can review — orgs + Private.
 * Backs the simplified main-window org picker.
 */
async listReviewableOrgs() : Promise<Result<ReviewableOrg[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_reviewable_orgs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a review session in the principal's chosen terminal, with
 * cwd set to the org's substrate root (or `~/.secretariat` for
 * Private). Passes `--agent review` to surface the org-local review
 * agent if one exists under `<org-root>/.claude/agents/review.md`.
 * 
 * `alias` is `_self` for Private, or the org's DNS-label alias.
 */
async reviewOrg(alias: string, terminal: string | null, command: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_org", { alias, terminal, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal a path in Finder (macOS) / file manager (other platforms).
 * 
 * Used by the Paths pane's "Reveal in Finder" button so the principal
 * can poke around in `~/.secretariat/` without us having to render a
 * file tree inside the app.
 */
async revealInFinder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_finder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all relays from `~/.secretariat/relay-state.json`. Returns an
 * empty vec if the file doesn't exist (pre-onboarding).
 */
async listRelays() : Promise<Result<RelayInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_relays") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add (or upsert) a relay endpoint. Does NOT register the principal's
 * DID with the relay — that happens automatically the first time
 * `invite` or `accept_invite` runs against this endpoint, or
 * (in CLI flows) via `sec relay register`.
 */
async addRelay(endpoint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_relay", { endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpIntegrationsStatus() : Promise<Result<IntegrationsStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_integrations_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run `sec mcp install` to re-wire Claude Code + Claude Desktop with
 * the current bundled binary. The principal hits this from the
 * Integrations pane when they see a path mismatch.
 */
async rewireMcpIntegrations() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rewire_mcp_integrations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the full preferences. Triggers migration from legacy files if needed.
 */
async getPreferences() : Promise<Result<PreferencesDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch composition settings (closing line + style notes).
 */
async setCompositionSettings(dto: CompositionSettingsDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_composition_settings", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch cognition settings (provider, API key, model, etc.).
 */
async setCognitionSettings(dto: CognitionSettingsDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cognition_settings", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch delivery settings (poll interval).
 */
async setDeliverySettings(dto: DeliverySettingsDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_delivery_settings", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Terminal app the principal wants the home-screen blob launcher to
 * use. None = `Terminal.app` default. Recognized: `terminal`,
 * `iterm`, `ghostty`. Anything else falls back to Terminal.app.
 */
assistant_terminal?: string | null; 
/**
 * Command the launcher runs inside the chosen terminal. None =
 * `claude` (Claude Code CLI). Lets the principal swap in another
 * MCP-aware client (`gemini`, `aider`, a script, etc.).
 */
assistant_command?: string | null }
export type CognitionSettingsDto = { provider: string; api_key: string | null; api_base: string | null; model: string | null; route_threshold: number | null }
export type CompositionSettingsDto = { closing_line: string; style_notes: string }
export type ContactListing = { did: string; display_name: string }
export type DeliverySettingsDto = { poll_interval_minutes: number }
export type EnvelopeListing = { file_path: string; from: string | null; 
/**
 * DID of the queue *owner* (recipient). Always set on well-formed
 * envelopes. UI compares to the principal's own DID to discriminate
 * local capture (`to == self`) from peer/channel post (`to != self`).
 */
to: string | null; 
/**
 * Queue handle on the owner's machine (`<namespace>:<slug>`). Always
 * set on well-formed envelopes alongside `to`. Direct messages
 * conventionally use `inbox:default`.
 */
queue: string | null; stamped: boolean; encrypted: boolean }
export type EnvelopeRead = { body: string; from: string | null; 
/**
 * DID of the queue *owner* (recipient).
 */
to: string | null; 
/**
 * Queue handle on the owner's machine (`<namespace>:<slug>`).
 */
queue: string | null; was_encrypted: boolean }
/**
 * What `init_identity` reports back to the front-end.
 */
export type IdentityState = { 
/**
 * The principal's DID — `did:key:z…` for a fresh install.
 */
did: string; 
/**
 * Whether this call generated a new identity (true) or surfaced an
 * existing one (false). The UI uses this to switch between
 * "Welcome — your identity is …" vs "Welcome back — you're …".
 */
created: boolean }
export type IntegrationStatus = { 
/**
 * Whether the integration is currently wired (server entry exists
 * in the client's config and points at the bundled `sec-mcp`).
 */
wired: boolean; 
/**
 * The path the integration's config currently points at, if any.
 * Useful for diagnostics — mismatch between this and the bundled
 * path means the silent-wire is stale.
 */
binary_path: string | null; 
/**
 * Where the integration stores its config (for surfacing in the UI).
 */
config_location: string | null; 
/**
 * Whether the client itself was detected at all (e.g. Claude Code
 * CLI installed, Claude Desktop app present).
 */
client_detected: boolean }
export type IntegrationsStatus = { claude_code: IntegrationStatus; claude_desktop: IntegrationStatus; 
/**
 * The path to the bundled `sec-mcp` we'd wire into clients.
 * When integrations show a different `binary_path`, the principal
 * can re-wire from the UI to bring them into sync.
 */
bundled_binary: string | null }
export type InviteClaimReport = { inviter_did: string; claimant_did: string; claimed_at: string; 
/**
 * True when the relay registered this principal as part of the claim
 * (first-time onboarding). False when the principal was already a tenant.
 */
registered: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type PreferencesDto = { composition: CompositionSettingsDto; cognition: CognitionSettingsDto; delivery: DeliverySettingsDto }
export type Profile = { display_name: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
export type RelayInfo = { endpoint: string; registered: boolean }
export type RelaySyncReport = { endpoint: string; inbound_count: number; auto_added_contacts: number; warnings: string[] }
/**
 * A reviewable organization the principal can dispatch a review session into.
 */
export type ReviewableOrg = { 
/**
 * `_self` for the private vault, alias DNS-label for orgs.
 */
alias: string; 
/**
 * Human-readable label rendered on the button.
 */
display_name: string; 
/**
 * Resolved working directory the review session will cd into.
 */
root_path: string }
/**
 * Stamp an outbox draft and (best-effort) deliver it immediately. Touch
 * ID fires from the app's window context. Returns the relay-assigned
 * id on successful delivery, or stamp metadata only if delivery fails
 * (the daemon's next sync tick retries — same fallback as the CLI's
 * stamp-immediate-send path).
 */
export type StampReport = { stamped_path: string; doc_hash: string; stamped_at: string; delivered: boolean; 
/**
 * Relay-assigned envelope ID. String to avoid BigInt/JS-number
 * roundtripping (specta forbids `u64` directly).
 */
relay_assigned_id: string | null; delivery_warning: string | null }
export type SyncReport = { per_relay: RelaySyncReport[]; sent_envelopes: number; outbox_warnings: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
