// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ensure the principal has an identity. Idempotent — generates a fresh
 * did:key on first call, returns the existing one thereafter.
 * 
 * Mirrors `sec init` (without the optional `--did did:web:...` flag, which
 * is a power-user case that can stay in the CLI for now).
 */
async initIdentity() : Promise<Result<IdentityState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Surface the current identity without generating one. Returns `None`
 * (serialized as `null`) if no identity exists yet — the front-end can
 * use this to decide whether to show onboarding or the main UI.
 */
async currentIdentity() : Promise<Result<IdentityState | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("current_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Provision a scribe (cognition-provider selection on Tauri onboarding).
 * 
 * Mirrors `sec agent add <name> --role scribe --substrate <substrate>`.
 * For `claude-code` substrate, the MCP wiring is already done at app
 * launch (per the bundled `sec mcp install` on boot — see AGENTS.md
 * "Tauri shell"); this command just provisions the agent identity.
 */
async provisionScribe(name: string, substrate: string) : Promise<Result<AgentDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("provision_scribe", { name, substrate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the principal's authorized scribes (and future agent roles).
 * Used by the onboarding screen to detect whether a scribe has already
 * been provisioned (returning to onboarding after a partial run should
 * show the existing scribe rather than offer to add another).
 */
async listScribes() : Promise<Result<AgentDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_scribes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diagnostic — returns the absolute path to `~/.secretariat/`. Useful for
 * "open in Finder" buttons and for surfacing where keys live.
 */
async secretariatRoot() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("secretariat_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Claim a correspondence invite from a deep link or HTTPS URL.
 * 
 * Accepts either form:
 * - `secretariat://<host>/v0/invite/<token>` (deep link from landing page)
 * - `https://<host>/v0/invite/<token>` (raw HTTPS URL the inviter shared)
 * 
 * Generates a fresh identity if none exists yet (so a deep link click is
 * the only step a first-time recipient needs). Maps to the existing
 * `secretariat-core::application::claim_invite` use case.
 */
async claimInviteUrl(deepLinkOrUrl: string) : Promise<Result<InviteClaimReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_invite_url", { deepLinkOrUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List received envelopes — walks the v0.3 substrate tree under
 * `~/.secretariat/` for every `envelopes/` directory and collects
 * the `.md` leaves.
 */
async listInbox() : Promise<Result<EnvelopeListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_inbox") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the principal's review queue — every envelope on disk under
 * any queue's `envelopes/YYYY/MM/DD/` tree. Post-Move 4 (substrate-
 * for-themia) drafts and federated envelopes share that tree; the
 * envelope frontmatter's `delivered:` field (absent = draft) is the
 * disambiguator. Both `to` and `queue` are populated on every
 * entry — discriminate local vs peer by comparing `to` to the
 * principal's own DID.
 */
async listReviewQueue() : Promise<Result<EnvelopeListing[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_review_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Decrypt + return the body of an envelope file. Plaintext envelopes
 * pass through unchanged; encrypted envelopes are decrypted using the
 * local signing key (key never leaves the device).
 */
async readEnvelope(filePath: string) : Promise<Result<EnvelopeRead, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run one sync cycle against every registered relay. Pulls inbound
 * envelopes on the principal's subscribed org channels. Principal-
 * initiated per the review-session model — no background push.
 * 
 * Idempotent and safe to call repeatedly. Returns a report the UI can
 * surface (counts + non-fatal warnings).
 */
async syncNow() : Promise<Result<SyncReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the principal's profile. Returns null when no identity is set
 * yet (fresh install pre-onboarding). Backed by `identity.md`
 * frontmatter (v0.7+).
 */
async getProfile() : Promise<Result<Profile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the principal's display name. Idempotent — overwrites whatever
 * was there. The DisplayName parser enforces validity (non-empty,
 * reasonable length, etc.).
 */
async setProfile(displayName: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_profile", { displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create an invite at the principal's first registered relay. Returns
 * the HTTPS claim URL the inviter shares (recipient's HTML landing
 * page lives at the same URL with `Accept: text/html`). Optional
 * `purpose` becomes the suggested contact name on the receiving side.
 */
async createInvite(purpose: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_invite", { purpose }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stampEnvelope(filePath: string) : Promise<Result<StampReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stamp_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an inbox envelope to `inbox/deferred/` — "remind me later".
 * Returns the new path. Idempotent.
 */
async deferInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("defer_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move an inbox envelope to `inbox/archived/` — "ignore / handled".
 * Returns the new path. Idempotent.
 */
async archiveInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reverse of `archive_inbox_envelope` — move a file from
 * `<queue>/archived/` back to `<queue>/envelopes/` (flat).
 */
async unarchiveInboxEnvelope(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_inbox_envelope", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawn the principal's assistant in their preferred environment. Reads
 * `AppPreferences::assistant_terminal` + `assistant_command` from the
 * caller; defaults to Terminal.app + `claude`.
 */
async launchAssistant(terminal: string | null, command: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_assistant", { terminal, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every vault the principal can review — orgs + Private.
 * Backs the simplified main-window org picker.
 */
async listReviewableOrgs() : Promise<Result<ReviewableOrg[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_reviewable_orgs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a review session in the principal's chosen terminal, with
 * cwd set to the org's substrate root (or `~/.secretariat` for
 * Private). Passes `--agent review` to surface the org-local review
 * agent if one exists under `<org-root>/.claude/agents/review.md`.
 * 
 * `alias` is `_self` for Private, or the org's DNS-label alias.
 */
async reviewOrg(alias: string, terminal: string | null, command: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("review_org", { alias, terminal, command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List every channel the principal can launch into.
 */
async listLaunchableChannels() : Promise<Result<LaunchableChannel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_launchable_channels") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new channel. Private (`_self`) when `org` is None;
 * org-scoped when supplied. Returns the resolved channel root path so
 * the caller can pop it open as a session tab immediately.
 */
async createChannel(handle: string, name: string, description: string, org: string | null) : Promise<Result<LaunchableChannel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_channel", { handle, name, description, org }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch a channel from the quick-pane via `sec launch` semantics
 * (binding-aware cwd + per-channel cognition overrides applied).
 */
async launchChannelFromPane(handle: string, org: string | null, terminal: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_channel_from_pane", { handle, org, terminal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Launch Claude at the channel-dir enclosing the given path. Walks up
 * until it finds the nearest `channel.md`; derives handle + org from
 * the path; then calls `launch_channel_from_pane` semantics.
 */
async launchClaudeAt(path: string, terminal: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_claude_at", { path, terminal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a channel hard-tree. Idempotent (no-ops if absent).
 */
async deleteChannel(handle: string, org: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_channel", { handle, org }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Capture an arbitrary blob of text to the `triage` queue from the quick-pane.
 */
async quickCapture(text: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quick_capture", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send one user message into a channel-scoped Claude session.
 * 
 * `session_id` is the caller-supplied stable handle. First turn for a
 * new conversation passes `is_first_turn=true`; the adapter generates
 * substrate state. Subsequent turns reuse the same `session_id` with
 * `is_first_turn=false` to resume.
 */
async sessionSend(tabId: string, channelPath: string, sessionId: string, message: string, isFirstTurn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_send", { tabId, channelPath, sessionId, message, isFirstTurn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel an in-flight turn. Idempotent.
 */
async sessionCancel(tabId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_cancel", { tabId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listExplorerRoots() : Promise<Result<TreeEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_explorer_roots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDir(path: string) : Promise<Result<TreeEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a directory or file on disk. The frontend supplies the
 * absolute current path and the new basename (not a full path). The
 * resulting path is the sibling of the original with the supplied
 * name. Intentionally minimal — no DID/handle rewriting, no envelope
 * fixups; the user is responsible for keeping consistency with the
 * channel handle if they rename a channel-dir.
 */
async renamePath(path: string, newName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_path", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move a directory or file under a new parent directory. The basename
 * is preserved (use `rename_path` first if you want to rename + move).
 * Intentionally minimal — no DID/handle rewriting, no envelope fixups.
 * The caller (frontend) is responsible for cycle / cross-root /
 * duplicate-name validation; this command also re-checks the cheap
 * invariants on the Rust side.
 */
async movePath(src: string, destParent: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_path", { src, destParent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Collect every envelope file path under the given root directory
 * — recursively walks any `envelopes/` subtree(s) and returns all
 * `.md` files. Used by the explorer to compute unread counts for
 * channel-leaf entries (and their parent folders by descendant
 * aggregation).
 * 
 * Bounded depth (16) to guard against pathological symlink loops.
 */
async listEnvelopesUnder(root: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_envelopes_under", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readChannelEnvelopes(channelPath: string, limit: number) : Promise<Result<EnvelopePreview[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_channel_envelopes", { channelPath, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reveal a path in Finder (macOS) / file manager (other platforms).
 * 
 * Used by the Paths pane's "Reveal in Finder" button so the principal
 * can poke around in `~/.secretariat/` without us having to render a
 * file tree inside the app.
 */
async revealInFinder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_finder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all relays from `~/.secretariat/relay-state.json`. Returns an
 * empty vec if the file doesn't exist (pre-onboarding).
 */
async listRelays() : Promise<Result<RelayInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_relays") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add (or upsert) a relay endpoint. Does NOT register the principal's
 * DID with the relay — that happens automatically the first time
 * `invite` or `accept_invite` runs against this endpoint, or
 * (in CLI flows) via `sec relay register`.
 */
async addRelay(endpoint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_relay", { endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpIntegrationsStatus() : Promise<Result<IntegrationsStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_integrations_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run `sec mcp install` to re-wire Claude Code + Claude Desktop with
 * the current bundled binary. The principal hits this from the
 * Integrations pane when they see a path mismatch.
 */
async rewireMcpIntegrations() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rewire_mcp_integrations") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read the full preferences. Triggers migration from legacy files if needed.
 */
async getPreferences() : Promise<Result<PreferencesDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch composition settings (closing line + style notes).
 */
async setCompositionSettings(dto: CompositionSettingsDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_composition_settings", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch cognition settings (provider, API key, model, etc.).
 */
async setCognitionSettings(dto: CognitionSettingsDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cognition_settings", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Patch delivery settings (poll interval).
 */
async setDeliverySettings(dto: DeliverySettingsDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_delivery_settings", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readMarkdown(path: string) : Promise<Result<ReadMarkdownResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_markdown", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeMarkdown(args: WriteMarkdownArgs) : Promise<Result<WriteMarkdownResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_markdown", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openMarkdownWindow(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_markdown_window", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takePendingOpens() : Promise<string[]> {
    return await TAURI_INVOKE("take_pending_opens");
},
/**
 * Check the configured update endpoint. Returns `None` when the app is
 * already on the latest version. Errors propagate as user-facing strings.
 */
async checkForUpdate() : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download + install the available update, then restart the app. No-op
 * (errors) when no update is pending — call `check_for_update` first.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentDto = { did: string; role: string; name: string; substrate: string; added_at: string }
/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Terminal app the principal wants the home-screen blob launcher to
 * use. None = `Terminal.app` default. Recognized: `terminal`,
 * `iterm`, `ghostty`. Anything else falls back to Terminal.app.
 */
assistant_terminal?: string | null; 
/**
 * Command the launcher runs inside the chosen terminal. None =
 * `claude` (Claude Code CLI). Lets the principal swap in another
 * MCP-aware client (`gemini`, `aider`, a script, etc.).
 */
assistant_command?: string | null }
export type CognitionSettingsDto = { provider: string; api_key: string | null; api_base: string | null; model: string | null; route_threshold: number | null }
export type CompositionSettingsDto = { closing_line: string; style_notes: string }
export type DeliverySettingsDto = { poll_interval_minutes: number }
export type EntryKind = 
/**
 * Top-level "Private" entry pointing at `_self`.
 */
"private" | 
/**
 * Top-level org root.
 */
"org" | 
/**
 * Directory containing a `channel.md` — clickable to open a session tab.
 */
"channel_leaf" | 
/**
 * Directory inside the channel tree without a `channel.md` (a non-leaf
 * handle segment, or a child dir like `envelopes/`).
 */
"dir" | 
/**
 * Regular file. The extension is exposed so the renderer can decide
 * how to open it (markdown editor for `.md`, Finder for others).
 */
"file"
export type EnvelopeListing = { file_path: string; from: string | null; 
/**
 * DID of the queue *owner* (recipient). Always set on well-formed
 * envelopes. UI compares to the principal's own DID to discriminate
 * local capture (`to == self`) from peer/channel post (`to != self`).
 */
to: string | null; 
/**
 * Queue handle on the owner's machine (`<namespace>:<slug>`). Always
 * set on well-formed envelopes alongside `to`. Direct messages
 * conventionally use `inbox:default`.
 */
queue: string | null; stamped: boolean; encrypted: boolean; 
/**
 * Delivery state marker from envelope frontmatter. `None` = draft
 * / undelivered (substrate-for-themia Move 4). `Some("<relay-seq-id>")`
 * = federated. `Some("local")` = self-owned channel that never
 * federates.
 */
delivered: string | null }
export type EnvelopePreview = { 
/**
 * Absolute path to the `.md` file — caller uses this to open the
 * envelope in a markdown tab.
 */
file_path: string; 
/**
 * Sender DID, when parseable from frontmatter.
 */
from: string | null; 
/**
 * Captured-at timestamp parsed from the filename (RFC 3339).
 */
at: string | null; 
/**
 * Free-form source tag, e.g. `idea-skill`, `mcp-capture`. Empty if
 * no envelope frontmatter.
 */
source: string; 
/**
 * True if a `$attestation` frontmatter block is present (stamped).
 */
stamped: boolean; 
/**
 * True if the body is a sealed wire form (cannot show plaintext
 * preview).
 */
encrypted: boolean; 
/**
 * First few lines of the body, plain text. Empty for encrypted
 * envelopes. The frontend renders this as markdown when the
 * envelope has no sender-declared `lede`.
 */
preview: string; 
/**
 * Filename basename — useful as a card title when no headline.
 */
filename: string; 
/**
 * Sender-declared AG headline (envelope.title). Optional.
 * Renderers SHOULD use this as the card title in timelines when
 * present; otherwise fall back to first heading / filename.
 */
title: string | null; 
/**
 * Sender-declared AG one-liner (envelope.lede). Optional.
 * Renderers SHOULD use this as the preview line in compact
 * timeline rows when present, in lieu of `preview` (body slice).
 */
lede: string | null; 
/**
 * Sender-declared AG multi-sentence summary (envelope.summary).
 * Optional. Surfaced in expanded views, not compact rows.
 */
summary: string | null }
export type EnvelopeRead = { body: string; from: string | null; 
/**
 * DID of the queue *owner* (recipient).
 */
to: string | null; 
/**
 * Queue handle on the owner's machine (`<namespace>:<slug>`).
 */
queue: string | null; was_encrypted: boolean }
/**
 * What `init_identity` reports back to the front-end.
 */
export type IdentityState = { 
/**
 * The principal's DID — `did:key:z…` for a fresh install.
 */
did: string; 
/**
 * Whether this call generated a new identity (true) or surfaced an
 * existing one (false). The UI uses this to switch between
 * "Welcome — your identity is …" vs "Welcome back — you're …".
 */
created: boolean }
export type IntegrationStatus = { 
/**
 * Whether the integration is currently wired (server entry exists
 * in the client's config and points at the bundled `sec-mcp`).
 */
wired: boolean; 
/**
 * The path the integration's config currently points at, if any.
 * Useful for diagnostics — mismatch between this and the bundled
 * path means the silent-wire is stale.
 */
binary_path: string | null; 
/**
 * Where the integration stores its config (for surfacing in the UI).
 */
config_location: string | null; 
/**
 * Whether the client itself was detected at all (e.g. Claude Code
 * CLI installed, Claude Desktop app present).
 */
client_detected: boolean }
export type IntegrationsStatus = { claude_code: IntegrationStatus; claude_desktop: IntegrationStatus; 
/**
 * The path to the bundled `sec-mcp` we'd wire into clients.
 * When integrations show a different `binary_path`, the principal
 * can re-wire from the UI to bring them into sync.
 */
bundled_binary: string | null }
export type InviteClaimReport = { inviter_did: string; claimant_did: string; claimed_at: string; 
/**
 * True when the relay registered this principal as part of the claim
 * (first-time onboarding). False when the principal was already a tenant.
 */
registered: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * A channel the principal can launch into from the quick-pane typeahead.
 */
export type LaunchableChannel = { handle: string; org: string | null; name: string; root_path: string; has_cognition_override: boolean }
export type PreferencesDto = { composition: CompositionSettingsDto; cognition: CognitionSettingsDto; delivery: DeliverySettingsDto }
export type Profile = { display_name: string }
export type ReadMarkdownResult = { content: string; sha256: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
export type RelayInfo = { endpoint: string; registered: boolean }
export type RelaySyncReport = { endpoint: string; inbound_count: number; warnings: string[] }
/**
 * A reviewable organization the principal can dispatch a review session into.
 */
export type ReviewableOrg = { 
/**
 * `_self` for the private vault, alias DNS-label for orgs.
 */
alias: string; 
/**
 * Human-readable label rendered on the button.
 */
display_name: string; 
/**
 * Resolved working directory the review session will cd into.
 */
root_path: string }
/**
 * Stamp a draft. Touch ID fires from the app's window context. The
 * stamp's atomic rename promotes the file into the canonical
 * `envelopes/YYYY/MM/DD/` day-shard, which is the daemon's wire-send
 * signal — federation runs in the daemon (substrate-for-themia,
 * Move 5).
 */
export type StampReport = { stamped_path: string; doc_hash: string; stamped_at: string; 
/**
 * Kept for backward compatibility with the frontend; always
 * `false` now that federation is daemon-only.
 */
delivered: boolean; 
/**
 * Kept for backward compatibility with the frontend; always
 * `None` now.
 */
relay_assigned_id: string | null; 
/**
 * Kept for backward compatibility with the frontend; always
 * `None` now.
 */
delivery_warning: string | null }
export type SyncReport = { per_relay: RelaySyncReport[] }
export type TreeEntry = { name: string; path: string; kind: EntryKind; 
/**
 * Cheap to compute; true for dirs that have at least one visible
 * child. Lets the tree render disclosure triangles without expanding.
 */
has_children: boolean; 
/**
 * True for directories that contain (at any depth) at least one
 * directory with a `channel.md`. Used by the frontend to filter
 * the tree to channel-only view, and to detect "parent channel"
 * entries (channel-leaves whose descendants include further
 * channel-leaves — those should expand/collapse, not open).
 */
has_channel_descendants: boolean; 
/**
 * Extension without the dot. Empty for dirs and extension-less files.
 */
ext: string; 
/**
 * For channel leaves: the handle string (joined by `:`). None
 * otherwise.
 */
handle: string | null; 
/**
 * For channel leaves under an org: the org alias. None for `_self`
 * or non-channel entries.
 */
org: string | null }
export type UpdateInfo = { 
/**
 * Version available on the update server.
 */
version: string; 
/**
 * Version currently running.
 */
current_version: string; 
/**
 * Release notes (markdown), if the manifest carries them.
 */
notes: string | null; 
/**
 * Release date as RFC3339 string, if present.
 */
date: string | null }
export type WriteMarkdownArgs = { path: string; content: string; expected_sha256: string }
export type WriteMarkdownResult = { kind: "ok"; sha256: string } | { kind: "conflict"; current_sha256: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
