//! In-process streaming cognition: multi-turn chat sessions.
//!
//! Today's only consumer is the Tauri tab-strip (per `project_mcp_is_primary_interface`
//! — UI navigates, MCP CRUDs; this port drives the navigation surface's
//! per-channel agent sessions). Future consumers: digest composer,
//! review co-pilot, scheduled agent loops.
//!
//! Sibling port [`CognitionLaunching`](super::launching::CognitionLaunching)
//! covers the *external-terminal* launch surface (`sec launch`); this
//! port covers *in-process* streaming chat. Adapters typically implement
//! one or the other — a substrate that drives via SDK calls (Claude
//! Agent SDK) implements `CognitionSession`; a substrate that the user
//! launches in a terminal (vanilla `claude` CLI, `ollama run`)
//! implements `CognitionLaunching`. Some substrates implement both.
//!
//! Event stream shape is deliberately structured: text deltas separated
//! from tool-call lifecycle separated from thinking, so renderers can
//! draw Slack-feel cards without parsing vendor stream-json formats.

use std::path::PathBuf;

use thiserror::Error;
use tokio::sync::mpsc::UnboundedSender;

/// Identifies one logical conversation. UUID generated by the caller
/// (frontend `crypto.randomUUID()`); the adapter persists state under
/// whatever path is natural for its substrate (e.g. Claude Code writes
/// to `$CLAUDE_CONFIG_DIR/projects/<encoded-cwd>/<session_id>.jsonl`).
#[derive(Debug, Clone)]
pub struct SessionRef {
    /// Stable session identifier. Same value across all turns of one
    /// conversation. Adapter creates substrate state on first turn,
    /// resumes it on subsequent.
    pub session_id: String,
    /// Working directory for cognition — usually the channel-dir.
    pub channel_dir: PathBuf,
    /// First turn for this `session_id`? Adapters differentiate
    /// "create new session" vs "resume existing" semantics.
    pub is_first_turn: bool,
    /// Optional per-session model override. None = adapter default.
    pub model: Option<String>,
}

#[derive(Debug, Clone)]
pub enum SessionEvent {
    /// One chunk of assistant-visible text. Concatenate in order.
    TextDelta(String),
    /// Adapter signaled the model invoking a tool. Renderers may show
    /// a "tool card" with input preview.
    ToolCallStart {
        id: String,
        name: String,
        input: serde_json::Value,
    },
    /// Tool finished; output payload follows.
    ToolCallResult {
        id: String,
        output: serde_json::Value,
    },
    /// Extended-thinking block. Some substrates emit nothing here.
    Thinking(String),
    /// Non-fatal warning surfaced to the principal.
    Warning(String),
    /// Turn complete. `stop_reason` is substrate-defined ("end_turn",
    /// "max_tokens", "tool_use", etc.); renderers may render it
    /// verbatim or ignore.
    Done { stop_reason: String },
}

#[derive(Debug, Error)]
pub enum SessionError {
    #[error("cognition session adapter not configured")]
    NotConfigured,
    /// Adapter process / sidecar isn't reachable. Caller surfaces and
    /// allows retry; conversation state stays intact for `--resume`.
    #[error("substrate unavailable: {0}")]
    Unavailable(String),
    /// Session `session_id` does not exist in adapter's store (e.g.
    /// `--resume` of a session the substrate never saw).
    #[error("unknown session: {0}")]
    UnknownSession(String),
    /// Adapter signaled the turn cannot be served (rate limit, quota,
    /// model unavailable).
    #[error("substrate refused turn: {0}")]
    Refused(String),
    #[error("internal: {0}")]
    Internal(String),
}

/// Drive a streaming multi-turn conversation. The adapter forwards
/// `SessionEvent`s through `events` as they arrive and resolves the
/// returned future only when the turn is fully processed (or errored).
///
/// Cancellation: caller can drop the receiver end of `events` and call
/// [`cancel`](CognitionSession::cancel) — the adapter must abort any
/// in-flight substrate work for that session id without poisoning the
/// session's substrate state (subsequent turns must still resume).
pub trait CognitionSession: Send + Sync {
    fn send_turn(
        &self,
        session: &SessionRef,
        message: String,
        events: UnboundedSender<SessionEvent>,
    ) -> impl std::future::Future<Output = Result<(), SessionError>> + Send;

    fn cancel(
        &self,
        session_id: &str,
    ) -> impl std::future::Future<Output = Result<(), SessionError>> + Send;
}
