use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        agent, explorer, markdown, notifications, preferences, quick_pane, recovery, secretariat,
        sessions, settings, timeline, updater,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        secretariat::init_identity,
        secretariat::current_identity,
        agent::provision_scribe,
        agent::list_scribes,
        secretariat::secretariat_root,
        secretariat::claim_invite_url,
        secretariat::list_inbox,
        secretariat::list_review_queue,
        secretariat::read_envelope,
        secretariat::get_profile,
        secretariat::set_profile,
        secretariat::create_invite,
        secretariat::stamp_envelope,
        secretariat::defer_inbox_envelope,
        secretariat::archive_inbox_envelope,
        secretariat::unarchive_inbox_envelope,
        secretariat::launch_assistant,
        secretariat::list_reviewable_orgs,
        secretariat::review_org,
        secretariat::list_launchable_channels,
        secretariat::create_channel,
        secretariat::launch_channel_from_pane,
        secretariat::launch_claude_at,
        secretariat::delete_channel,
        secretariat::quick_capture,
        sessions::session_send,
        sessions::session_cancel,
        explorer::list_explorer_roots,
        explorer::list_dir,
        explorer::rename_path,
        explorer::move_path,
        explorer::list_envelopes_under,
        timeline::read_channel_envelopes,
        settings::reveal_in_finder,
        settings::list_relays,
        settings::mcp_integrations_status,
        settings::rewire_mcp_integrations,
        settings::get_preferences,
        settings::set_composition_settings,
        settings::set_cognition_settings,
        settings::set_delivery_settings,
        markdown::read_markdown,
        markdown::write_markdown,
        markdown::open_markdown_window,
        markdown::take_pending_opens,
        updater::check_for_update,
        updater::install_update,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
